export const medios = [
    "El País",
    "elDiario.es",
    "Público",
    "La Razón",
    "RTVE",
    "Electomanía",
    "Cadena SER",
    "ABC",
    "El Periódico de Getafe",
    "Radio 5",
    "europa press",
    "EFE:",
    "Aiudo",
    "Expansión",
];