export const news = 
[
    {
        'id': '0',
        'title': 'Resultados de las Elecciones Municipales 2023',
        'link': 'https://www.publico.es/resultados-elecciones/municipales/2023/',
        'organizations': ['Todos'],
        'date': '2023/05/29 00:00',
        'tags': ['Elecciones'],
        'media': 'Público',
        'national': 'si'
    },
    {
        'id': '1',
        'title': 'Ayuso sube el precio de los comedores escolares en los colegios públicos y eleva el gasto diario de las familias a 5,50 euros',
        'link': 'https://www.publico.es/sociedad/ayuso-sube-precio-comedores-escolares-colegios-publicos-eleva-gasto-diario-familias-5-50-euros.html',
        'organizations': ['Partido Popular'],
        'provincia': 'Comunidad de Madrid',
        'date': '2023/05/30',
        'tags': ['Educación'],
        'media': 'Público'
    },
    {
        'id': '2',
        'title': 'Más de 10.000 niños se quedan sin plaza en las escuelas infantiles de Madrid un día después de las elecciones ',
        'link': 'https://www.eldiario.es/madrid/somos/miles-ninos-quedan-plaza-escuelas-infantiles-madrid-dia-despues-elecciones_1_10249261.html',
        'organizations': ['Partido Popular'],
        'alcaldia': 'Madrid',
        'date': '2023/05/30',
        'tags': ['Educación'],
        'media': 'elDiario.es'
    },
    {
        'id': '3',
        'title': 'El Gobierno reconoce los verdiales de Málaga como patrimonio inmaterial de la cultura en España',
        'link': 'https://cadenaser.com/andalucia/2023/05/30/el-gobierno-reconoce-los-verdiales-de-malaga-como-patrimonio-inmaterial-de-la-cultura-en-espana-ser-malaga/',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/30',
        'tags': ['Medio ambiente'],
        'media': 'Cadena SER',
        'national': 'si'
    },
    {
        'id': '4',
        'title': 'Sánchez se reúne en Moncloa con el administrador de la NASA y firma la adhesión de España al programa Artemis',
        'link': 'https://www.europapress.es/nacional/noticia-sanchez-reune-moncloa-administrador-nasa-firma-adhesion-espana-programa-artemis-20230530165501.html?utm_campaign=smartclip_social&utm_medium=Social&utm_source=Twitter',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/30',
        'tags': ['Ciencia'],
        'media': 'europa press',
        'national': 'si'
    },
    {
        'id': '5',
        'title': 'Sanidad da luz verde a una alternativa a la quimioterapia intravenosa en el cáncer de mama',
        'link': 'https://www.abc.es/salud/sanidad-luz-verde-alternativa-quimioterapia-intravenosa-cancer-20230530164902-nt.html#vca=rrss&vmc=abc-es&vso=tw&vli=cm-general&_tcode=d3RwMGoy',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/30',
        'tags': ['Sanidad'],
        'media': 'ABC',
        'national': 'si'
    },
    {
        'id': '6',
        'title': 'Sánchez anuncia la disolución de las Cortes y la convocatoria de elecciones anticipadas el 23 de julio',
        'link': 'https://www.publico.es/politica/sanchez-anuncia-disolucion-cortes-convocatoria-elecciones-anticipadas.html',
        'organizations': ['Partido Socialista Obrero Español'],
        'date': '2023/05/29 22:00',
        'tags': ['Elecciones'],
        'media': 'Público',
        'national': 'si'
    },
    {
        'id': '7',
        'title': 'Sumar se constituye como partido para poder presentarse a las elecciones',
        'link': 'https://www.expansion.com/economia/politica/elecciones-generales/2023/05/30/6475f275468aebae778b45e5.html',
        'organizations': ['Movimiento Sumar'],
        'date': '2023/05/30',
        'tags': ['Elecciones'],
        'media': 'Expansión',
        'national': 'si'
    },
    {
        'id': '8',
        'title': 'Primer “arboricidio” de Almeida después de las elecciones: vecinos de Carabanchel denuncian la tala de grandes acacias',
        'link': 'https://www.eldiario.es/madrid/somos/primer-arboricidio-almeida-despues-elecciones-vecinos-carabanchel-denuncian-tala-grandes-acacias_1_10255542.html',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'alcaldia': 'Madrid',
        'tags': ['Medio ambiente'],
        'media': 'elDiario.es',
    },
    {
        'id': '9',
        'title': 'El Ayuntamiento de Madrid tramita echar abajo una antigua iglesia del barrio de Letras para abrir un hotel',
        'link': 'https://www.eldiario.es/madrid/somos/ayuntamiento-madrid-tramita-echar-abajo-antigua-iglesia-barrio-letras-abrir-hotel_1_10251769.html',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'alcaldia': 'Madrid',
        'tags': ['Urbanismo'],
        'media': 'elDiario.es',
    },
    {
        'id': '10',
        'title': 'Moreno da plantón a la sesión de control del Parlamento andaluz para asistir a la final de la Europa League',
        'link': 'https://www.eldiario.es/andalucia/moreno-plante-sesion-control-parlamento-andaluz-asistir-final-liga-europea_1_10254579.html',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'autonomia': 'Andalucía',
        'tags': ['Pleno'],
        'media': 'elDiario.es',
    },
    {
        'id': '11',
        'title': 'Un pueblo salmantino se rebela contra las elecciones del 23 de julio',
        'link': 'https://www.larazon.es/castilla-y-leon/pueblo-salmantino-rebela-elecciones-23-julio_20230531647726be21debe0001928bb3.html?utm_source=twitter&utm_medium=organic&utm_campaign=lrzn_org_We_12_58',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'alcaldia': 'Tabera de Abajo',
        'tags': ['Elecciones'],
        'media': 'La Razón',
    },
    {
        'id': '12',
        'title': 'Se buscan premios Nobel para un contrato en la universidad por meses y sin sueldo definido: razón, Castilla y León',
        'link': 'https://elpais.com/educacion/2023-05-31/se-buscan-premios-nobel-para-un-contrato-en-la-universidad-por-meses-y-sin-sueldo-definido-razon-castilla-y-leon.html?utm_medium=social&utm_campaign=echobox&utm_source=Twitter&ssm=TW_CM#Echobox=1685546216-1',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/05/31',
        'autonomia': 'Castilla y León',
        'tags': ['Educación'],
        'media': 'El País',
    },
    {
        'id': '13',
        'title': 'Macarena Olona registra el partido Caminando Juntos para presentarse a las elecciones generales del 23 de julio',
        'link': 'https://cadenaser.com/nacional/2023/05/31/macarena-olona-se-presenta-a-las-elecciones-generales-con-el-partido-caminando-juntos-cadena-ser/',
        'organizations': ['Caminando Juntos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Elecciones'],
        'media': 'Cadena SER',
    },
    {
        'id': '14',
        'title': 'Educación paraliza la nueva EBAU a la espera de las elecciones generales del 23 de julio',
        'link': 'https://www.rtve.es/noticias/20230531/paralizada-nueva-ebau/2448083.shtml',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Educación'],
        'media': 'RTVE',
    },
    {
        'id': '15',
        'title': 'Cultura convoca 70 plazas para vigilantes de sala de museos',
        'link': 'https://www.europapress.es/cultura/exposiciones-00131/noticia-cultura-convoca-70-plazas-vigilantes-sala-museos-20230531151320.html',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Cultura'],
        'media': 'europa press',
    },
    {
        'id': '16',
        'title': 'El derecho a paro de las empleadas del hogar queda en suspensión como consecuencia del anticipo de las elecciones del 23J',
        'link': 'https://aiudo.es/leyes-suspendidas-derecho-paro-empleadas-hogar-elecciones-anticipadas/',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Empleo'],
        'media': 'Aiudo',
    },
    {
        'id': '17',
        'title': 'Ayuso destina dos millones de euros a un ‘cheque canguro’ para contratar empleadas del hogar',
        'link': 'https://elpais.com/espana/madrid/2023-06-01/ayuso-destina-dos-millones-de-euros-a-un-cheque-canguro-para-contratar-empleados-del-hogar.html?utm_medium=social&utm_campaign=echobox&utm_source=Twitter&ssm=TW_CM#Echobox=1685626639',
        'organizations': ['Partido Popular'],
        'date': '2023/06/01',
        'provincia': 'Comunidad de Madrid',
        'tags': ['Servicios sociales'],
        'media': 'El País',
    },
    {
        'id': '18',
        'title': 'España emite una queja formal ante Rabat por llamar a Ceuta y Melilla «ciudades marroquíes»',
        'link': 'https://www.abc.es/espana/espana-emite-queja-formal-ante-rabat-llamar-20230531210053-nt.html#vca=rrss&vmc=abc-es&vso=tw&vli=cm-general&_tcode=YzJ2azQz',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/01',
        'national': 'si',
        'tags': ['Internacional'],
        'media': 'ABC',
    },
    {
        'id': '19',
        'title': 'El PP apoya una propuesta de ley impulsada por EH Bildu en el Parlamento vasco',
        'link': 'https://elpais.com/espana/2023-06-01/el-pp-apoya-una-propuesta-de-ley-impulsada-por-eh-bildu-en-el-parlamento-vasco.html?ssm=TW_CM&utm_campaign=echobox&utm_medium=social&utm_source=Twitter#Echobox=1685622707',
        'organizations': ['Partido Popular', 'EH Bildu'],
        'date': '2023/06/01',
        'autonomia': 'País Vasco',
        'tags': ['Medio ambiente'],
        'media': 'El País',
    },
    {
        'id': '20',
        'title': 'El Parlamento andaluz aprueba con votos de PP y Vox crear las dos primeras universidades privadas bajo el mandato de Moreno',
        'link': 'https://www.eldiario.es/andalucia/parlamento-aprueba-votos-pp-vox-crear-primeras-universidades-privadas-mandato-moreno_1_10258015.html',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/01',
        'autonomia': 'Andalucía',
        'tags': ['Educación', 'Urbanismo'],
        'media': 'elDiario.es',
    },
    {
        'id': '21',
        'title': 'PP y Vox votan en Bruselas contra una ley para evitar la explotación laboral y el trabajo infantil',
        'link': 'https://www.eldiario.es/politica/pp-vox-votan-bruselas-ley-evitar-explotacion-laboral-trabajo-infantil_1_10259761.html',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/01',
        'national': 'si',
        'tags': ['Internacional', 'Empleo'],
        'media': 'elDiario.es',
    },
    {
        'id': '22',
        'title': 'El Ministerio de Sanidad impulsa el Proyecto Ready To Ship, que enviará unidades de sangre de cordón umbilical a pacientes que necesiten un trasplante urgente',
        'link': 'https://twitter.com/radio5_rne/status/1664649555831410693?t=ZrE-LHWWG9wUrPC5pWLlHg&s=35',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/02',
        'national': 'si',
        'tags': ['Sanidad'],
        'media': 'Radio 5',
    },
    {
        'id': '23',
        'title': 'El PP da marcha atrás para permitir que el presidente del Consejo de Doñana comparezca finalmente en el Parlamento',
        'link': 'https://www.eldiario.es/andalucia/pp-da-marcha-permitir-presidente-consejo-donana-comparezca-finalmente-parlamento_1_10262406.html',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/02',
        'autonomia': 'Andalucía',
        'tags': ['Medio ambiente'],
        'media': 'elDiario.es',
    },
    {
        'id': '24',
        'title': 'Andalucía instala un dispositivo único en España para evitar el atropello de animales',
        'link': 'https://www.europapress.es/esandalucia/huelva/noticia-andalucia-instala-dispositivo-unico-espana-evitar-atropello-animales-20230602141053.html?utm_campaign=smartclip_social&utm_medium=Social&utm_source=Twitter',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/02',
        'autonomia': 'Andalucía',
        'tags': ['Medio ambiente'],
        'media': 'europa press',
    },
    {
        'id': '25',
        'title': 'Sánchez retrasa la presentación en Bruselas de la presidencia española de la UE por el 23J',
        'link': 'https://efe.com/espana/2023-06-02/sanchez-retraso-comparecencia-eurocamara/',
        'organizations': ['Partido Socialista Obrero Español'],
        'date': '2023/06/02',
        'national': 'si',
        'tags': ['Internacional'],
        'media': 'EFE:',
    },
    {
        'id': '26',
        'title': 'Interior gasta casi 900.000 euros en sanidad privada para presos por falta de médicos penitenciarios',
        'link': 'https://elpais.com/sociedad/2023-06-02/interior-gasta-casi-900000-euros-en-sanidad-privada-para-presos-por-falta-de-medicos-penitenciarios.html',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/02',
        'national': 'si',
        'tags': ['Sanidad'],
        'media': 'El País',
    },
    {
        'id': '27',
        'title': 'Castilla y León ignora la orden del Gobierno central sobre los controles a la tuberculosis bovina',
        'link': 'https://www.publico.es/politica/castilla-leon-ignora-orden-gobierno-central-controles-tuberculosis-bovina.html?utm_term=Autofeed&utm_campaign=Publico&utm_medium=social&utm_source=Twitter#Echobox=1685684102',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/01',
        'autonomia': 'Castilla y León',
        'tags': ['Sanidad', 'Medio ambiente'],
        'media': 'Público',
    },
    {
        'id': '28',
        'title': 'La Comunidad de Madrid prorroga los contratos “del hambre” en las residencias hasta marzo de 2024',
        'link': 'https://elpais.com/espana/madrid/2023-06-03/la-comunidad-de-madrid-prorroga-los-contratos-del-hambre-en-las-residencias-hasta-marzo-de-2024.html?utm_medium=social&utm_campaign=echobox&utm_source=Twitter&ssm=TW_CM#Echobox=1685946200-1',
        'organizations': ['Partido Popular'],
        'date': '2023/06/03',
        'autonomia': 'Comunidad de Madrid',
        'tags': ['Sanidad', 'Servicios sociales'],
        'media': 'El País',
    },
    {
        'id': '29',
        'title': 'Condenan a un ayuntamiento de Canarias por la muerte de un hombre al auxiliar a una bañista',
        'link': 'https://cadenaser.com/canarias/2023/06/05/condenan-a-un-ayuntamiento-de-canarias-por-la-muerte-de-un-hombre-al-auxiliar-a-una-banista-ser-las-palmas/',
        'organizations': ['Gana Fuerteventura', 'Partido Popular'],
        'date': '2023/06/05',
        'alcaldia': 'La Oliva',
        'tags': ['Condenas'],
        'media': 'Cadena SER',
    },
    {
        'id': '30',
        'title': 'El Gobierno aprueba un plan para blindar los derechos humanos en España frente a la crisis climática y la precariedad',
        'link': 'https://www.eldiario.es/politica/gobierno-aprueba-plan-blindar-derechos-humanos-espana-frente-crisis-climatica-precariedad_1_10266032.html',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/04',
        'national': 'si',
        'tags': ['Internacional', 'Servicios sociales', 'Igualdad', 'Medio ambiente', 'Tecnología'],
        'media': 'elDiario.es',
    },
    {
        'id': '31',
        'title': 'Coalición Canaria y PP anuncian un acuerdo de gobierno en el Cabildo de Tenerife con Rosa Dávila como presidenta',
        'link': 'https://cadenaser.com/canarias/2023/06/05/cc-y-pp-anuncian-un-acuerdo-de-gobierno-en-el-cabildo-de-tenerife-con-rosa-davila-como-presidenta-radio-club-tenerife/',
        'organizations': ['Coalición Canaria', 'Partido Popular'],
        'date': '2023/06/05',
        'provincia': 'Santa Cruz de Tenerife',
        'tags': ['Elecciones'],
        'media': 'Cadena SER',
    },
    {
        'id': '32',
        'title': 'La Comunidad de Madrid paga 2,8 millones a una inmobiliaria participada por familiares de Esperanza Aguirre',
        'link': 'https://www.eldiario.es/economia/comunidad-madrid-paga-2-8-millones-inmobiliaria-participada-familiares-esperanza-aguirre_1_10261946.html',
        'organizations': ['Partido Popular'],
        'date': '2023/06/05',
        'autonomia': 'Comunidad de Madrid',
        'tags': ['Urbanismo'],
        'media': 'elDiario.es',
    },
    {
        'id': '33',
        'title': 'Andalucía autoriza, en el Día Mundial del Medio Ambiente, que Fertibería tape los fosfoyesos de Huelva sin trasladarlos',
        'link': 'https://www.eldiario.es/andalucia/huelva/andalucia-autoriza-dia-mundial-medio-ambiente-fertiberia-tape-fosfoyesos-huelva-trasladarlos_1_10269246.html',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/05',
        'autonomia': 'Andalucía',
        'tags': ['Medio ambiente'],
        'media': 'elDiario.es',
    },
    {
        'id': '34',
        'title': 'Una moneda de un euro decide el alcalde de un alcaldia gallego',
        'link': 'https://www.abc.es/espana/galicia/moneda-euro-decide-alcalde-alcaldia-gallego-20230605194413-nt.html#vca=rrss&vmc=abc-es&vso=tw&vli=cm-general&_tcode=Ymw2bjUz',
        'organizations': ['Partido Popular', 'Partido Socialista Obrero Español'],
        'date': '2023/06/05',
        'alcaldia': 'Arcos da Condesa',
        'tags': ['Elecciones'],
        'media': 'ABC',
    },
    {
        'id': '35',
        'title': 'Baldoví descarta volver al Congreso: "Sería faltar al respeto a los electores" ',
        'link': 'https://twitter.com/LaHoraTVE/status/1665985121995079680',
        'organizations': ['Compromís'],
        'date': '2023/06/06',
        'national': 'si',
        'tags': ['Elecciones'],
        'media': 'RTVE',
    },
    {
        'id': '36',
        'title': 'El presidente de las Cortes de Castilla y León (Vox) nombra a un amigo de Santiago Abascal como su jefe de gabinete',
        'link': 'https://www.eldiario.es/castilla-y-leon/politica/presidente-cortes-castilla-leon-nombra-amigo-santiago-abascal-jefe-gabinete_1_10266974.html',
        'organizations': ['Vox'],
        'date': '2023/06/05',
        'autonomia': 'Castilla y León',
        'tags': ['Elecciones'],
        'media': 'elDiario.es',
    },
    {
        'id': '37',
        'title': 'El Gobierno aprueba la adenda al Plan de Recuperación para recibir 10.300 millones más en transferencias y 84.000 en préstamos',
        'link': 'https://www.eldiario.es/economia/gobierno-aprueba-adenda-plan-recuperacion-recibir-10-000-millones-transferencias-84-000-prestamos_1_10270810.html',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/06',
        'national': 'si',
        'tags': ['Economía'],
        'media': 'elDiario.es',
    },
    {
        'id': '38',
        'title': 'El Parlamento andaluz amplía con Delibes los comparecientes por la ley de regadíos en torno a Doñana con rechazo de Vox',
        'link': 'https://electomania.es/el-parlamento-andaluz-amplia-con-delibes-los-comparecientes-por-la-ley-de-regadios-6j23/',
        'organizations': ['Vox'],
        'date': '2023/06/06',
        'autonomia': 'Andalucía',
        'tags': ['Medio ambiente'],
        'media': 'Electomanía',
    },
    {
        'id': '39',
        'title': 'Dedocracia: el Madrid de Ayuso oculta el 77% de los currículum de sus altos cargos',
        'link': 'https://www.publico.es/politica/dedocracia-madrid-ayuso-oculta-77-curriculum-altos-cargos.html?utm_medium=social&utm_campaign=Publico&utm_source=Twitter#Echobox=1686045762-1',
        'organizations': ['Partido Popular', 'Compromís', 'Podemos', 'Partido Socialista Obrero Español'],
        'date': '2023/06/03',
        'national': 'si',
        'tags': ['Economía'],
        'media': 'Público',
    },
    {
        'id': '40',
        'title': 'Los primeros representantes cannábicos de Europa están en Murillo el Fruto (Navarra)',
        'link': 'https://cadenaser.com/navarra/2023/06/04/los-primeros-representantes-cannabicos-de-europa-estan-en-murillo-el-fruto-navarra-radio-pamplona/',
        'organizations': ['Luz Verde'],
        'date': '2023/06/04',
        'alcaldia': 'Murillo el Fruto',
        'tags': ['Elecciones'],
        'media': 'Cadena SER',
    },
    {
        'id': '41',
        'title': 'El Ayuntamiento formaliza por 1,8 millones el servicio del sistema de gestión de una Zona de Bajas Emisiones',
        'link': 'https://periodicogetafe.blogspot.com/2023/05/el-ayuntamiento-formaliza-por-18.html?spref=tw',
        'organizations': ['Partido Socialista Obrero Español', 'Podemos'],
        'date': '2023/06/03',
        'alcaldia': 'Getafe',
        'tags': ['Medio ambiente'],
        'media': 'El Periódico de Getafe',
    },
    {
        'id': '42',
        'title': 'El Gobierno anula por innecesaria tras vencer en los tribunales la orden que limitó el movimiento de ganado en Castilla y León',
        'link': 'https://www.eldiario.es/politica/politica-directo-ultima-hora_6_10273412_1100659.html',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/07',
        'national': 'si',
        'tags': ['Medio ambiente'],
        'media': 'elDiario.es',
    },
    {
        'id': '43',
        'title': 'El Gobierno archiva las multas por más de 10.000 euros a las mujeres que pidieron el indulto de María Salmerón',
        'link': 'https://www.publico.es/mujer/gobierno-archiva-multas-10000-euros-mujeres-pidieron-indulto-maria-salmeron.html?utm_term=Autofeed&utm_campaign=Publico&utm_medium=social&utm_source=Twitter#Echobox=1686115780',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/07',
        'national': 'si',
        'tags': ['Legal'],
        'media': 'Público',
    },
    {
        'id': '44',
        'title': 'El Gobierno no informa del acuerdo migratorio con Biden',
        'link': 'https://www.larazon.es/espana/gobierno-informa-acuerdo-migratorio-biden_20230607647cf1dc45377c0001743aa5.html?utm_source=twitter&utm_medium=organic&utm_campaign=lrzn_org_We_8_15',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/07',
        'national': 'si',
        'tags': ['Inmigración'],
        'media': 'La Razón',
    },
    {
        'id': '45',
        'title': 'Agricultura dicta medidas de protección por el brote de gripe aviar en L’Albufera de Valencia',
        'link': 'https://elpais.com/espana/comunidad-valenciana/2023-06-08/agricultura-dicta-medidas-de-proteccion-por-el-brote-de-gripe-aviar-en-lalbufera-de-valencia.html?ssm=TW_CC',
        'organizations': ['Partido Socialista Obrero Español', 'Podemos', 'Compromís'],
        'date': '2023/06/08',
        'autonomia': 'Comunidad Valenciana',
        'tags': ['Medio ambiente', 'Sanidad'],
        'media': 'El País',
    },
    {
        'id': '46',
        'title': 'El Supremo condena a Montero a indemnizar a la expareja de la expresidenta de Infancia Libre por llamarle "maltratador"',
        'link': 'https://www.rtve.es/noticias/20230609/supremo-condena-montero-indemnizar-expareja-expresidenta-infancia-libre-llamarle-maltratador/2449025.shtml',
        'organizations': ['Unidas Podemos'],
        'date': '2023/06/09',
        'national': 'si',
        'tags': ['Condenas'],
        'media': 'RTVE',
    },
    {
        'id': '47',
        'title': 'Una residencia rebajada de precio por el “alcalde más votado” sube sus cuotas dos días después del 28-M',
        'link': 'https://elpais.com/espana/madrid/2023-06-09/una-residencia-rebajada-de-precio-por-el-alcalde-mas-votado-sube-sus-cuotas-dos-dias-despues-del-28-m.html?utm_medium=social&utm_campaign=echobox&utm_source=Twitter&ssm=TW_CM#Echobox=1686302476-1',
        'organizations': ['Partido Popular'],
        'date': '2023/06/09',
        'alcaldia': 'Torrejón de Ardoz',
        'tags': ['Servicios sociales'],
        'media': 'El País',
    },
    {
        'id': '48',
        'title': 'Las bases de Podemos avalan con un 93% de los votos que la dirección decida si pacta con Sumar',
        'link': 'https://www.eldiario.es/politica/bases-avalan-93-direccion-cierre-acuerdo-sumar_1_10280276.html',
        'organizations': ['Podemos'],
        'date': '2023/06/09',
        'national': 'si',
        'tags': ['Elecciones'],
        'media': 'elDiario.es',
    },
    {
        'id': '49',
        'title': 'Yolanda Díaz impone una cláusula contra una escisión de Podemos: si se van pierden el 23% del dinero de la coalición',
        'link': 'https://www.elmundo.es/elecciones/elecciones-generales/2023/06/11/64845858fdddff6b868b45ce.html?cid=BESOCYEM01&utm_source=twitter&utm_medium=social_besocy&utm_campaign=BESOCYEM01',
        'organizations': ['Sumar', 'Podemos'],
        'date': '2023/06//11',
        'national': 'si',
        'tags': ['Elecciones'],
        'media': 'El Mundo',
    },
    {
        'id': '50',
        'title': 'Ayuso elimina el descuento para el Abono Transporte mientras da ayudas a ricos para servicio doméstic',
        'link': 'https://www.elplural.com/autonomias/madrid/ayuso-elimina-descuento-abono-transporte-mientras-da-ayudas-ricos-servicio-domestico_312302102',
        'organizations': ['Partido Popular'],
        'date': '2023/06/11',
        'autonomia': 'Comunidad de Madrid',
        'tags': ['Transporte'],
        'media': 'elplural',
    },
    {
        'id': '51',
        'title': 'Llegan los buzones de denuncia anónima: claves y límites de una medida que abre una nueva etapa contra la corrupción',
        'link': 'https://www.eldiario.es/tecnologia/llegan-buzones-denuncia-anonima-claves-limites-medida-abre-nueva-etapa-corrupcion_1_10286860.html',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/12',
        'national': 'si',
        'tags': ['Empleo', 'Corrupción'],
        'media': 'elDiario.es',
    },
    {
        'id': '52',
        'title': 'Vox y PP vetan la bandera LGTBI en edificios públicos de Nàquera y la condena oficial a “la violencia machista”',
        'link': 'https://www.eldiario.es/comunitat-valenciana/valencia/vox-pp-vetan-bandera-lgtbiq-edificios-publicos-naquera-condena-oficial-violencia-machista_1_10310881.html',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/21',
        'alcaldia': 'Náquera',
        'tags': ['Igualdad'],
        'media': 'elDiario.es',
    },
    {
        'id': '53',
        'title': 'La bandera LGTBI deja de ondear en Torrijos tras la llegada al Ayuntamiento de PP y Vox: "Es un acto simbólico que alimenta el odio"',
        'link': 'https://toledodiario.es/la-bandera-lgtbi-deja-de-ondear-en-torrijos-tras-la-llegada-al-ayuntamiento-de-pp-y-vox-es-un-acto-simbolico-que-alimenta-el-odio/',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/20',
        'alcaldia': 'Torrijos',
        'tags': ['Igualdad'],
        'media': 'toledodiario.es',
    },
    {
        'id': '54',
        'title': 'PP y Vox retiran la bandera LGTBI del Ayuntamiento de la localidad granadina de Vegas del Genil',
        'link': 'https://www.eldiario.es/andalucia/granada/pp-vox-retiran-bandera-lgtbi-ayuntamiento-vegas-genil-granada_1_10313832.html',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/21',
        'alcaldia': 'Vegas del Genil',
        'tags': ['Igualdad'],
        'media': 'elDiario.es',
    },
    {
        'id': '55',
        'title': 'El PP suprime la concejalía de Igualdad en Elche y una candidata antiabortista de Vox gestionará la de Familia y Mayores',
        'link': 'https://www.eldiario.es/comunitat-valenciana/pp-suprime-concejalia-igualdad-elche-crear-familia-mayores-gestionara-candidata-antiabortista-vox_1_10309364.html',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/06/20',
        'alcaldia': 'Elche',
        'tags': ['Igualdad'],
        'media': 'elDiario.es',
    },
    {
        'id': '56',
        'title': 'Ayuso da 30,5 millones a becas de la FP privada mientras 30.000 alumnos se quedan sin plaza pública',
        'link': 'https://www.publico.es/politica/ayuso-destina-30-5-millones-becas-fp-privada-30000-alumnos-quedan-plaza-publica.html?utm_medium=social&utm_campaign=Publico&utm_source=Twitter#Echobox=1686758840',
        'organizations': ['Partido Popular'],
        'date': '2023/06/14',
        'autonomia': 'Comunidad de Madrid',
        'tags': ['Educación'],
        'media': 'Público',
    },
    {
        'id': '57',
        'title': 'Yolanda Díaz y los sindicatos presentan el estatuto del becario para atajar precariedad en las prácticas',
        'link': 'https://cadenaser.com/nacional/2023/06/15/yolanda-diaz-y-los-sindicatos-presentan-el-estatuto-del-becario-para-atajar-precariedad-en-las-practicas-cadena-ser/',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/06/15',
        'national': 'si',
        'tags': ['Trabajo', 'Educación'],
        'media': 'Cadena SER',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    {
        'id': '',
        'title': '',
        'link': '',
        'organizations': [''],
        'date': '',
        'alcaldia': '',
        'tags': [''],
        'media': '',
    },
    // {
    //     'id': '',
    //     'title': '',
    //     'link': '',
    //     'organizations': [''],
    //     'date': '',
    //     'alcaldia': '',
    //     'tags': [''],
    //     'media': '',
    // },
]