export const news = 
[
    {
        'id': '0',
        'title': 'Resultados de las Elecciones Municipales 2023',
        'link': 'https://www.publico.es/resultados-elecciones/municipales/2023/',
        'organizations': ['Todos'],
        'date': '2023/05/29 00:00',
        'tags': ['Elecciones'],
        'media': 'Público',
        'national': 'si'
    },
    {
        'id': '1',
        'title': 'Ayuso sube el precio de los comedores escolares en los colegios públicos y eleva el gasto diario de las familias a 5,50 euros',
        'link': 'https://www.publico.es/sociedad/ayuso-sube-precio-comedores-escolares-colegios-publicos-eleva-gasto-diario-familias-5-50-euros.html',
        'organizations': ['Partido Popular'],
        'provincia': 'Comunidad de Madrid',
        'date': '2023/05/30',
        'tags': ['Educación'],
        'media': 'Público'
    },
    {
        'id': '2',
        'title': 'Más de 10.000 niños se quedan sin plaza en las escuelas infantiles de Madrid un día después de las elecciones ',
        'link': 'https://www.eldiario.es/madrid/somos/miles-ninos-quedan-plaza-escuelas-infantiles-madrid-dia-despues-elecciones_1_10249261.html',
        'organizations': ['Partido Popular'],
        'alcaldia': 'Madrid',
        'date': '2023/05/30',
        'tags': ['Educación'],
        'media': 'elDiario.es'
    },
    {
        'id': '3',
        'title': 'El Gobierno reconoce los verdiales de Málaga como patrimonio inmaterial de la cultura en España',
        'link': 'https://cadenaser.com/andalucia/2023/05/30/el-gobierno-reconoce-los-verdiales-de-malaga-como-patrimonio-inmaterial-de-la-cultura-en-espana-ser-malaga/',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/30',
        'tags': ['Medio ambiente'],
        'media': 'Cadena SER',
        'national': 'si'
    },
    {
        'id': '4',
        'title': 'Sánchez se reúne en Moncloa con el administrador de la NASA y firma la adhesión de España al programa Artemis',
        'link': 'https://www.europapress.es/nacional/noticia-sanchez-reune-moncloa-administrador-nasa-firma-adhesion-espana-programa-artemis-20230530165501.html?utm_campaign=smartclip_social&utm_medium=Social&utm_source=Twitter',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/30',
        'tags': ['Ciencia'],
        'media': 'europa press',
        'national': 'si'
    },
    {
        'id': '5',
        'title': 'Sanidad da luz verde a una alternativa a la quimioterapia intravenosa en el cáncer de mama',
        'link': 'https://www.abc.es/salud/sanidad-luz-verde-alternativa-quimioterapia-intravenosa-cancer-20230530164902-nt.html#vca=rrss&vmc=abc-es&vso=tw&vli=cm-general&_tcode=d3RwMGoy',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/30',
        'tags': ['Sanidad'],
        'media': 'ABC',
        'national': 'si'
    },
    {
        'id': '6',
        'title': 'Sánchez anuncia la disolución de las Cortes y la convocatoria de elecciones anticipadas el 23 de julio',
        'link': 'https://www.publico.es/politica/sanchez-anuncia-disolucion-cortes-convocatoria-elecciones-anticipadas.html',
        'organizations': ['Partido Socialista Obrero Español'],
        'date': '2023/05/29 22:00',
        'tags': ['Elecciones'],
        'media': 'Público',
        'national': 'si'
    },
    {
        'id': '7',
        'title': 'Sumar se constituye como partido para poder presentarse a las elecciones',
        'link': 'https://www.expansion.com/economia/politica/elecciones-generales/2023/05/30/6475f275468aebae778b45e5.html',
        'organizations': ['Movimiento Sumar'],
        'date': '2023/05/30',
        'tags': ['Elecciones'],
        'media': 'Expansión',
        'national': 'si'
    },
    {
        'id': '8',
        'title': 'Primer “arboricidio” de Almeida después de las elecciones: vecinos de Carabanchel denuncian la tala de grandes acacias',
        'link': 'https://www.eldiario.es/madrid/somos/primer-arboricidio-almeida-despues-elecciones-vecinos-carabanchel-denuncian-tala-grandes-acacias_1_10255542.html',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'alcaldia': 'Madrid',
        'tags': ['Medio ambiente'],
        'media': 'elDiario.es',
    },
    {
        'id': '9',
        'title': 'El Ayuntamiento de Madrid tramita echar abajo una antigua iglesia del barrio de Letras para abrir un hotel',
        'link': 'https://www.eldiario.es/madrid/somos/ayuntamiento-madrid-tramita-echar-abajo-antigua-iglesia-barrio-letras-abrir-hotel_1_10251769.html',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'alcaldia': 'Madrid',
        'tags': ['Urbanismo'],
        'media': 'elDiario.es',
    },
    {
        'id': '10',
        'title': 'Moreno da plantón a la sesión de control del Parlamento andaluz para asistir a la final de la Europa League',
        'link': 'https://www.eldiario.es/andalucia/moreno-plante-sesion-control-parlamento-andaluz-asistir-final-liga-europea_1_10254579.html',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'autonomia': 'Andalucía',
        'tags': ['Pleno'],
        'media': 'elDiario.es',
    },
    {
        'id': '11',
        'title': 'Un pueblo salmantino se rebela contra las elecciones del 23 de julio',
        'link': 'https://www.larazon.es/castilla-y-leon/pueblo-salmantino-rebela-elecciones-23-julio_20230531647726be21debe0001928bb3.html?utm_source=twitter&utm_medium=organic&utm_campaign=lrzn_org_We_12_58',
        'organizations': ['Partido Popular'],
        'date': '2023/05/31',
        'alcaldia': 'Tabera de Abajo',
        'tags': ['Elecciones'],
        'media': 'La Razón',
    },
    {
        'id': '12',
        'title': 'Se buscan premios Nobel para un contrato en la universidad por meses y sin sueldo definido: razón, Castilla y León',
        'link': 'https://elpais.com/educacion/2023-05-31/se-buscan-premios-nobel-para-un-contrato-en-la-universidad-por-meses-y-sin-sueldo-definido-razon-castilla-y-leon.html?utm_medium=social&utm_campaign=echobox&utm_source=Twitter&ssm=TW_CM#Echobox=1685546216-1',
        'organizations': ['Partido Popular', 'Vox'],
        'date': '2023/05/31',
        'autonomia': 'Castilla y León',
        'tags': ['Educación'],
        'media': 'El País',
    },
    {
        'id': '13',
        'title': 'Macarena Olona registra el partido Caminando Juntos para presentarse a las elecciones generales del 23 de julio',
        'link': 'https://cadenaser.com/nacional/2023/05/31/macarena-olona-se-presenta-a-las-elecciones-generales-con-el-partido-caminando-juntos-cadena-ser/',
        'organizations': ['Caminando Juntos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Elecciones'],
        'media': 'Cadena SER',
    },
    {
        'id': '14',
        'title': 'Educación paraliza la nueva EBAU a la espera de las elecciones generales del 23 de julio',
        'link': 'https://www.rtve.es/noticias/20230531/paralizada-nueva-ebau/2448083.shtml',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Educación'],
        'media': 'RTVE',
    },
    {
        'id': '15',
        'title': 'Cultura convoca 70 plazas para vigilantes de sala de museos',
        'link': 'https://www.europapress.es/cultura/exposiciones-00131/noticia-cultura-convoca-70-plazas-vigilantes-sala-museos-20230531151320.html',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Cultura'],
        'media': 'europa press',
    },
    {
        'id': '16',
        'title': 'El derecho a paro de las empleadas del hogar queda en suspensión como consecuencia del anticipo de las elecciones del 23J',
        'link': 'https://aiudo.es/leyes-suspendidas-derecho-paro-empleadas-hogar-elecciones-anticipadas/',
        'organizations': ['Partido Socialista Obrero Español', 'Unidas Podemos'],
        'date': '2023/05/31',
        'national': 'si',
        'tags': ['Empleo'],
        'media': 'Aiudo',
    },
    // {
    //     'id': '',
    //     'title': '',
    //     'link': '',
    //     'organizations': [''],
    //     'date': '2023/05/31',
    //     'autonomia': '',
    //     'tags': [''],
    //     'media': '',
    // },
]